-- Seed data: HPCRMS branches and fleet (United States)
-- Uses ON CONFLICT so this is safe to run every startup without duplicating
-- rows. For an existing database with the OLD Jamaica seed data already
-- committed, this will NOT retroactively rename those rows (ON CONFLICT
-- DO NOTHING only skips inserts, it never updates) — see the accompanying
-- migration notes for how to fully refresh an existing dev database.

INSERT INTO branches (name, address, city, phone) VALUES
('LAX Airport', '1 World Way', 'Los Angeles, CA', '310-555-0101'),
('JFK Airport', 'JFK Airport Terminal 4', 'Queens, NY', '718-555-0102'),
('Miami Airport', '2100 NW 42nd Ave', 'Miami, FL', '305-555-0103'),
('O''Hare Airport', '10000 W Balmoral Ave', 'Chicago, IL', '773-555-0104'),
('Honolulu Airport', '300 Rodgers Blvd', 'Honolulu, HI', '808-555-0105'),
('Dallas Downtown', '1401 Elm St', 'Dallas, TX', '214-555-0106'),
('Orlando Airport', '1 Jeff Fuqua Blvd', 'Orlando, FL', '407-555-0107')
ON CONFLICT (name) DO NOTHING;

INSERT INTO vehicles (license_plate, make, model, category, branch_id, daily_rate, status, mileage, image_url) VALUES
('CA1001', 'Toyota', 'Yaris', 'ECONOMY', (SELECT id FROM branches WHERE name = 'LAX Airport'), 38.39, 'AVAILABLE', 4639, '/vehicle-images/economy.svg'),
('NY1002', 'Honda', 'Fit', 'ECONOMY', (SELECT id FROM branches WHERE name = 'JFK Airport'), 39.42, 'AVAILABLE', 19049, '/vehicle-images/economy.svg'),
('FL1003', 'Nissan', 'Versa', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Miami Airport'), 34.23, 'AVAILABLE', 9717, '/vehicle-images/economy.svg'),
('IL1004', 'Kia', 'Rio', 'ECONOMY', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 38.77, 'AVAILABLE', 38741, '/vehicle-images/economy.svg'),
('HI1005', 'Chevrolet', 'Spark', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 32.87, 'AVAILABLE', 30651, '/vehicle-images/economy.svg'),
('TX1006', 'Hyundai', 'Accent', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 32.32, 'AVAILABLE', 9140, '/vehicle-images/economy.svg'),
('FL1007', 'Mitsubishi', 'Mirage', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 34.19, 'AVAILABLE', 36118, '/vehicle-images/economy.svg'),
('CA1008', 'Toyota', 'Yaris', 'ECONOMY', (SELECT id FROM branches WHERE name = 'LAX Airport'), 38.02, 'AVAILABLE', 39781, '/vehicle-images/economy.svg'),
('NY1009', 'Honda', 'Fit', 'ECONOMY', (SELECT id FROM branches WHERE name = 'JFK Airport'), 33.99, 'AVAILABLE', 38713, '/vehicle-images/economy.svg'),
('FL1010', 'Nissan', 'Versa', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Miami Airport'), 36.2, 'AVAILABLE', 32439, '/vehicle-images/economy.svg'),
('IL1011', 'Kia', 'Rio', 'ECONOMY', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 37.89, 'AVAILABLE', 3425, '/vehicle-images/economy.svg'),
('HI1012', 'Chevrolet', 'Spark', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 39.59, 'AVAILABLE', 13463, '/vehicle-images/economy.svg'),
('TX1013', 'Hyundai', 'Accent', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 38.98, 'AVAILABLE', 25298, '/vehicle-images/economy.svg'),
('FL1014', 'Mitsubishi', 'Mirage', 'ECONOMY', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 34.78, 'AVAILABLE', 17110, '/vehicle-images/economy.svg'),
('CA1015', 'Toyota', 'Yaris', 'ECONOMY', (SELECT id FROM branches WHERE name = 'LAX Airport'), 41.57, 'AVAILABLE', 25059, '/vehicle-images/economy.svg'),
('NY1016', 'Toyota', 'Corolla', 'COMPACT', (SELECT id FROM branches WHERE name = 'JFK Airport'), 41.23, 'AVAILABLE', 27898, '/vehicle-images/compact.svg'),
('FL1017', 'Honda', 'Civic', 'COMPACT', (SELECT id FROM branches WHERE name = 'Miami Airport'), 41.16, 'AVAILABLE', 25541, '/vehicle-images/compact.svg'),
('IL1018', 'Nissan', 'Sentra', 'COMPACT', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 47.24, 'AVAILABLE', 5847, '/vehicle-images/compact.svg'),
('HI1019', 'Mazda', 'Mazda3', 'COMPACT', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 48.76, 'AVAILABLE', 38142, '/vehicle-images/compact.svg'),
('TX1020', 'Hyundai', 'Elantra', 'COMPACT', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 41.5, 'AVAILABLE', 27807, '/vehicle-images/compact.svg'),
('FL1021', 'Kia', 'Forte', 'COMPACT', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 40.95, 'AVAILABLE', 22213, '/vehicle-images/compact.svg'),
('CA1022', 'Chevrolet', 'Cruze', 'COMPACT', (SELECT id FROM branches WHERE name = 'LAX Airport'), 49.95, 'AVAILABLE', 26700, '/vehicle-images/compact.svg'),
('NY1023', 'Toyota', 'Corolla', 'COMPACT', (SELECT id FROM branches WHERE name = 'JFK Airport'), 46.93, 'AVAILABLE', 7558, '/vehicle-images/compact.svg'),
('FL1024', 'Honda', 'Civic', 'COMPACT', (SELECT id FROM branches WHERE name = 'Miami Airport'), 40.55, 'AVAILABLE', 17935, '/vehicle-images/compact.svg'),
('IL1025', 'Nissan', 'Sentra', 'COMPACT', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 49.28, 'AVAILABLE', 8229, '/vehicle-images/compact.svg'),
('HI1026', 'Mazda', 'Mazda3', 'COMPACT', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 50.26, 'AVAILABLE', 9619, '/vehicle-images/compact.svg'),
('TX1027', 'Hyundai', 'Elantra', 'COMPACT', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 44.56, 'AVAILABLE', 32714, '/vehicle-images/compact.svg'),
('FL1028', 'Kia', 'Forte', 'COMPACT', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 47.63, 'AVAILABLE', 26909, '/vehicle-images/compact.svg'),
('CA1029', 'Chevrolet', 'Cruze', 'COMPACT', (SELECT id FROM branches WHERE name = 'LAX Airport'), 41.95, 'AVAILABLE', 26283, '/vehicle-images/compact.svg'),
('NY1030', 'Toyota', 'Corolla', 'COMPACT', (SELECT id FROM branches WHERE name = 'JFK Airport'), 42.51, 'AVAILABLE', 20496, '/vehicle-images/compact.svg'),
('FL1031', 'Toyota', 'Camry', 'SEDAN', (SELECT id FROM branches WHERE name = 'Miami Airport'), 63.23, 'AVAILABLE', 7679, '/vehicle-images/sedan.svg'),
('IL1032', 'Honda', 'Accord', 'SEDAN', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 61.75, 'AVAILABLE', 14215, '/vehicle-images/sedan.svg'),
('HI1033', 'Nissan', 'Altima', 'SEDAN', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 60.55, 'AVAILABLE', 19043, '/vehicle-images/sedan.svg'),
('TX1034', 'Ford', 'Fusion', 'SEDAN', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 54.61, 'AVAILABLE', 27867, '/vehicle-images/sedan.svg'),
('FL1035', 'Hyundai', 'Sonata', 'SEDAN', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 56.32, 'AVAILABLE', 39500, '/vehicle-images/sedan.svg'),
('CA1036', 'Kia', 'K5', 'SEDAN', (SELECT id FROM branches WHERE name = 'LAX Airport'), 55.51, 'AVAILABLE', 24252, '/vehicle-images/sedan.svg'),
('NY1037', 'Chevrolet', 'Malibu', 'SEDAN', (SELECT id FROM branches WHERE name = 'JFK Airport'), 65.49, 'AVAILABLE', 6665, '/vehicle-images/sedan.svg'),
('FL1038', 'Toyota', 'Camry', 'SEDAN', (SELECT id FROM branches WHERE name = 'Miami Airport'), 55.66, 'AVAILABLE', 5103, '/vehicle-images/sedan.svg'),
('IL1039', 'Honda', 'Accord', 'SEDAN', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 64.88, 'AVAILABLE', 29290, '/vehicle-images/sedan.svg'),
('HI1040', 'Nissan', 'Altima', 'SEDAN', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 56.28, 'AVAILABLE', 16826, '/vehicle-images/sedan.svg'),
('TX1041', 'Ford', 'Fusion', 'SEDAN', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 66.61, 'AVAILABLE', 40170, '/vehicle-images/sedan.svg'),
('FL1042', 'Hyundai', 'Sonata', 'SEDAN', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 66.02, 'AVAILABLE', 23622, '/vehicle-images/sedan.svg'),
('CA1043', 'Kia', 'K5', 'SEDAN', (SELECT id FROM branches WHERE name = 'LAX Airport'), 55.4, 'AVAILABLE', 35717, '/vehicle-images/sedan.svg'),
('NY1044', 'Chevrolet', 'Malibu', 'SEDAN', (SELECT id FROM branches WHERE name = 'JFK Airport'), 58.33, 'AVAILABLE', 33071, '/vehicle-images/sedan.svg'),
('FL1045', 'Toyota', 'Camry', 'SEDAN', (SELECT id FROM branches WHERE name = 'Miami Airport'), 54.29, 'AVAILABLE', 12150, '/vehicle-images/sedan.svg'),
('IL1046', 'Toyota', 'RAV4', 'SUV', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 67.67, 'AVAILABLE', 39789, '/vehicle-images/suv.svg'),
('HI1047', 'Honda', 'CR-V', 'SUV', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 74.4, 'AVAILABLE', 41311, '/vehicle-images/suv.svg'),
('TX1048', 'Ford', 'Escape', 'SUV', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 71.85, 'AVAILABLE', 41242, '/vehicle-images/suv.svg'),
('FL1049', 'Chevrolet', 'Equinox', 'SUV', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 71.19, 'AVAILABLE', 17373, '/vehicle-images/suv.svg'),
('CA1050', 'Nissan', 'Rogue', 'SUV', (SELECT id FROM branches WHERE name = 'LAX Airport'), 84.94, 'AVAILABLE', 12065, '/vehicle-images/suv.svg'),
('NY1051', 'Jeep', 'Cherokee', 'SUV', (SELECT id FROM branches WHERE name = 'JFK Airport'), 73.72, 'AVAILABLE', 8957, '/vehicle-images/suv.svg'),
('FL1052', 'Hyundai', 'Tucson', 'SUV', (SELECT id FROM branches WHERE name = 'Miami Airport'), 79.38, 'AVAILABLE', 10185, '/vehicle-images/suv.svg'),
('IL1053', 'Toyota', 'RAV4', 'SUV', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 65.52, 'AVAILABLE', 13484, '/vehicle-images/suv.svg'),
('HI1054', 'Honda', 'CR-V', 'SUV', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 80.22, 'AVAILABLE', 30666, '/vehicle-images/suv.svg'),
('TX1055', 'Ford', 'Escape', 'SUV', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 75.72, 'AVAILABLE', 28216, '/vehicle-images/suv.svg'),
('FL1056', 'Chevrolet', 'Equinox', 'SUV', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 70.78, 'AVAILABLE', 33674, '/vehicle-images/suv.svg'),
('CA1057', 'Nissan', 'Rogue', 'SUV', (SELECT id FROM branches WHERE name = 'LAX Airport'), 74.17, 'AVAILABLE', 39256, '/vehicle-images/suv.svg'),
('NY1058', 'Jeep', 'Cherokee', 'SUV', (SELECT id FROM branches WHERE name = 'JFK Airport'), 81.8, 'AVAILABLE', 3752, '/vehicle-images/suv.svg'),
('FL1059', 'Hyundai', 'Tucson', 'SUV', (SELECT id FROM branches WHERE name = 'Miami Airport'), 77.65, 'AVAILABLE', 10507, '/vehicle-images/suv.svg'),
('IL1060', 'Toyota', 'RAV4', 'SUV', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 77.68, 'AVAILABLE', 38190, '/vehicle-images/suv.svg'),
('HI1061', 'Ford', 'F-150', 'TRUCK', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 98.27, 'AVAILABLE', 25293, '/vehicle-images/truck.svg'),
('TX1062', 'Chevrolet', 'Silverado', 'TRUCK', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 81.01, 'AVAILABLE', 31492, '/vehicle-images/truck.svg'),
('FL1063', 'Ram', '1500', 'TRUCK', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 82.27, 'AVAILABLE', 3212, '/vehicle-images/truck.svg'),
('CA1064', 'Toyota', 'Tacoma', 'TRUCK', (SELECT id FROM branches WHERE name = 'LAX Airport'), 103.75, 'AVAILABLE', 20261, '/vehicle-images/truck.svg'),
('NY1065', 'GMC', 'Sierra', 'TRUCK', (SELECT id FROM branches WHERE name = 'JFK Airport'), 104.24, 'AVAILABLE', 14708, '/vehicle-images/truck.svg'),
('FL1066', 'Nissan', 'Titan', 'TRUCK', (SELECT id FROM branches WHERE name = 'Miami Airport'), 91.71, 'AVAILABLE', 9973, '/vehicle-images/truck.svg'),
('IL1067', 'Toyota', 'Tundra', 'TRUCK', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 101.5, 'AVAILABLE', 22558, '/vehicle-images/truck.svg'),
('HI1068', 'Ford', 'F-150', 'TRUCK', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 100.73, 'AVAILABLE', 36270, '/vehicle-images/truck.svg'),
('TX1069', 'Chevrolet', 'Silverado', 'TRUCK', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 94.44, 'AVAILABLE', 13016, '/vehicle-images/truck.svg'),
('FL1070', 'Ram', '1500', 'TRUCK', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 88.1, 'AVAILABLE', 13587, '/vehicle-images/truck.svg'),
('CA1071', 'Toyota', 'Tacoma', 'TRUCK', (SELECT id FROM branches WHERE name = 'LAX Airport'), 92.56, 'AVAILABLE', 37757, '/vehicle-images/truck.svg'),
('NY1072', 'GMC', 'Sierra', 'TRUCK', (SELECT id FROM branches WHERE name = 'JFK Airport'), 102.8, 'AVAILABLE', 24243, '/vehicle-images/truck.svg'),
('FL1073', 'Nissan', 'Titan', 'TRUCK', (SELECT id FROM branches WHERE name = 'Miami Airport'), 91.19, 'AVAILABLE', 10331, '/vehicle-images/truck.svg'),
('IL1074', 'Toyota', 'Tundra', 'TRUCK', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 103.09, 'AVAILABLE', 23153, '/vehicle-images/truck.svg'),
('HI1075', 'Ford', 'F-150', 'TRUCK', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 84.47, 'AVAILABLE', 18785, '/vehicle-images/truck.svg'),
('TX1076', 'BMW', '3 Series', 'LUXURY', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 158.29, 'AVAILABLE', 8161, '/vehicle-images/luxury.svg'),
('FL1077', 'Mercedes-Benz', 'C-Class', 'LUXURY', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 114.71, 'AVAILABLE', 34849, '/vehicle-images/luxury.svg'),
('CA1078', 'Audi', 'A4', 'LUXURY', (SELECT id FROM branches WHERE name = 'LAX Airport'), 154.88, 'AVAILABLE', 37911, '/vehicle-images/luxury.svg'),
('NY1079', 'Lexus', 'ES', 'LUXURY', (SELECT id FROM branches WHERE name = 'JFK Airport'), 152.12, 'AVAILABLE', 11414, '/vehicle-images/luxury.svg'),
('FL1080', 'Cadillac', 'CT5', 'LUXURY', (SELECT id FROM branches WHERE name = 'Miami Airport'), 146.29, 'AVAILABLE', 39031, '/vehicle-images/luxury.svg'),
('IL1081', 'Genesis', 'G70', 'LUXURY', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 119.08, 'AVAILABLE', 37581, '/vehicle-images/luxury.svg'),
('HI1082', 'Infiniti', 'Q50', 'LUXURY', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 157.98, 'AVAILABLE', 30730, '/vehicle-images/luxury.svg'),
('TX1083', 'BMW', '3 Series', 'LUXURY', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 163.04, 'AVAILABLE', 38343, '/vehicle-images/luxury.svg'),
('FL1084', 'Mercedes-Benz', 'C-Class', 'LUXURY', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 151.54, 'AVAILABLE', 16182, '/vehicle-images/luxury.svg'),
('CA1085', 'Audi', 'A4', 'LUXURY', (SELECT id FROM branches WHERE name = 'LAX Airport'), 149.21, 'AVAILABLE', 29148, '/vehicle-images/luxury.svg'),
('NY1086', 'Lexus', 'ES', 'LUXURY', (SELECT id FROM branches WHERE name = 'JFK Airport'), 164.73, 'AVAILABLE', 27472, '/vehicle-images/luxury.svg'),
('FL1087', 'Cadillac', 'CT5', 'LUXURY', (SELECT id FROM branches WHERE name = 'Miami Airport'), 134.1, 'AVAILABLE', 36919, '/vehicle-images/luxury.svg'),
('IL1088', 'Genesis', 'G70', 'LUXURY', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 134.83, 'AVAILABLE', 19246, '/vehicle-images/luxury.svg'),
('HI1089', 'Infiniti', 'Q50', 'LUXURY', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 122.36, 'AVAILABLE', 25156, '/vehicle-images/luxury.svg'),
('TX1090', 'BMW', '3 Series', 'LUXURY', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 111.16, 'AVAILABLE', 39301, '/vehicle-images/luxury.svg'),
('FL1091', 'Chrysler', 'Pacifica', 'VAN', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 77.29, 'AVAILABLE', 17432, '/vehicle-images/van.svg'),
('CA1092', 'Honda', 'Odyssey', 'VAN', (SELECT id FROM branches WHERE name = 'LAX Airport'), 72.17, 'AVAILABLE', 6858, '/vehicle-images/van.svg'),
('NY1093', 'Toyota', 'Sienna', 'VAN', (SELECT id FROM branches WHERE name = 'JFK Airport'), 77.27, 'AVAILABLE', 5058, '/vehicle-images/van.svg'),
('FL1094', 'Kia', 'Carnival', 'VAN', (SELECT id FROM branches WHERE name = 'Miami Airport'), 91.77, 'AVAILABLE', 7643, '/vehicle-images/van.svg'),
('IL1095', 'Dodge', 'Grand Caravan', 'VAN', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 83.83, 'AVAILABLE', 21250, '/vehicle-images/van.svg'),
('HI1096', 'Ford', 'Transit', 'VAN', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 87.39, 'AVAILABLE', 17040, '/vehicle-images/van.svg'),
('TX1097', 'Chevrolet', 'Express', 'VAN', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 84.4, 'AVAILABLE', 40423, '/vehicle-images/van.svg'),
('FL1098', 'Chrysler', 'Pacifica', 'VAN', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 85.25, 'AVAILABLE', 18925, '/vehicle-images/van.svg'),
('CA1099', 'Honda', 'Odyssey', 'VAN', (SELECT id FROM branches WHERE name = 'LAX Airport'), 90.05, 'AVAILABLE', 29677, '/vehicle-images/van.svg'),
('NY1100', 'Toyota', 'Sienna', 'VAN', (SELECT id FROM branches WHERE name = 'JFK Airport'), 76.38, 'AVAILABLE', 9352, '/vehicle-images/van.svg'),
('FL1101', 'Kia', 'Carnival', 'VAN', (SELECT id FROM branches WHERE name = 'Miami Airport'), 87.16, 'AVAILABLE', 26219, '/vehicle-images/van.svg'),
('IL1102', 'Dodge', 'Grand Caravan', 'VAN', (SELECT id FROM branches WHERE name = 'O''Hare Airport'), 81.74, 'AVAILABLE', 33606, '/vehicle-images/van.svg'),
('HI1103', 'Ford', 'Transit', 'VAN', (SELECT id FROM branches WHERE name = 'Honolulu Airport'), 91.87, 'AVAILABLE', 6550, '/vehicle-images/van.svg'),
('TX1104', 'Chevrolet', 'Express', 'VAN', (SELECT id FROM branches WHERE name = 'Dallas Downtown'), 87.49, 'AVAILABLE', 9449, '/vehicle-images/van.svg'),
('FL1105', 'Chrysler', 'Pacifica', 'VAN', (SELECT id FROM branches WHERE name = 'Orlando Airport'), 73.39, 'AVAILABLE', 25236, '/vehicle-images/van.svg')
ON CONFLICT (license_plate) DO NOTHING;
